function main () {
    i = 0
    try {
        write x
    }
    except {
        write "went into except"
    }
} fin